#!/bin/sh

set -e

# Live-build configuration for RoxieOS Roxanne v0.1
# Based on Debian Trixie, optimized for cyberdeck workflow

LB_CONFIG_VERSION="20240102"
LB_DISTRIBUTION="trixie"
LB_ARCHITECTURES="amd64"
LB_BOOTSTRAP_QEMU_ARCHITECTURES="amd64"
LB_MODE="debian"
LB_SECURITY="true"
LB_UPDATES="true"
LB_BACKPORTS="false"
LB_SOURCE="false"

# Build options
LB_BUILD_WITH_CHROOT="true"
LB_BUILD_WITH_TMPFS="true"
LB_CACHE="true"
LB_CACHE_PACKAGES="true"
LB_CACHE_STAGES="bootstrap rootfs"

# Debian package tasks
LB_TASKS="standard"

# Firmware and kernel
LB_LINUX_FLAVOURS="amd64"
LB_LINUX_PACKAGES="linux-image-roxanne"

# Bootloader
LB_BOOTLOADERS="grub-efi grub-pc"
LB_GRUB_SPLASH="roxiewallpaper.png"

# Compression
LB_COMPRESSION="gzip"

# Checksums
LB_CHECKSUMS="sha256"

# ISO options
LB_ISO_APPLICATION="RoxieOS Roxanne"
LB_ISO_PREPARER="groksroxieos"
LB_ISO_PUBLISHER="Roxanne Cyberdeck"
LB_ISO_VOLUME="ROXIEOS_ROXANNE"