#!/bin/sh

# $FreeBSD$
#
# PROVIDE: baux-shot
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="baux_shot"
rcvar="baux_shot_enable"

load_rc_config $name

: ${baux_shot_enable:=NO}

run_rc_command "$1"